/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-15 07:28:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t<!DOCTYPE html>\r\n");
      out.write("\t<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    <title>HOME</title>\t\r\n");
      out.write("        <!-- Required meta tags -->\r\n");
      out.write("        <meta charset=\"ISO-8859-1\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Bootstrap CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://bootswatch.com/4/slate/bootstrap.min.css\" >\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Nunito\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\" integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/index-style.css\">\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"CSS/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("        <title>Homepage</title>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body onload=\"startTime()\">\r\n");
      out.write("\r\n");
      out.write("        <!--- Clock Display ------> \r\n");
      out.write("        <script>\r\n");
      out.write("            function startTime() {\r\n");
      out.write("                var today = new Date();\r\n");
      out.write("                var h = today.getHours();\r\n");
      out.write("                var m = today.getMinutes();\r\n");
      out.write("                var s = today.getSeconds();\r\n");
      out.write("                m = checkTime(m);\r\n");
      out.write("                s = checkTime(s);\r\n");
      out.write("                document.getElementById('txt').innerHTML =\r\n");
      out.write("                        h + \":\" + m + \":\" + s;\r\n");
      out.write("                var t = setTimeout(startTime, 500);\r\n");
      out.write("            }\r\n");
      out.write("            function checkTime(i) {\r\n");
      out.write("                if (i < 10) {\r\n");
      out.write("                    i = \"0\" + i\r\n");
      out.write("                }\r\n");
      out.write("                ;  // add zero in front of numbers < 10\r\n");
      out.write("                return i;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <!------------------------------->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"preloader bg-dark text-light\" >\r\n");
      out.write("            <div class=\"preloader-spinner\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div id=\"header-top\" class=\"d-none d-xl-block\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"loader-content\">\r\n");
      out.write("                                <!--<img src=\"assets/img/preloader.gif\">-->\r\n");
      out.write("                                <p id=\"txt\"></p>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-left \">\r\n");
      out.write("                                <i class=\"fas fa-map-marker-alt\"></i> &nbsp; Orex Shopping Complex, Ja-Ela\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"fas fa-phone-volume\"></i> 0112 249 249\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"far fa-clock\"></i> Mon-Fri 09.00 - 17.00\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"header-social-icons text-right\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-facebook\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>&nbsp;\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t\t<div class=\"col-lg-4\">\r\n");
      out.write("                        <a href=\"Home.jsp\" class=\"logo\">\r\n");
      out.write("                            <img src=\"CSS/img/logo.png\" alt=\"JSOFT\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("  \t\t<div class=\"collapse navbar-collapse\" id=\"navbarColor02\">\r\n");
      out.write("    \t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("        <li class=\"nav-item active\">\r\n");
      out.write("        <a href=\"Home.jsp\" class=\"nav-link\" href=\"#\">HOME </a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"vehicles.jsp\" class=\"nav-link\" href=\"#\">AVAILABLE VEHICLES</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("         <a href=\"booking.html\" class=\"nav-link\" href=\"#\">BOOK A CAR</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"contactus.html\" class=\"nav-link\" href=\"#\">CONTACT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"aboutus.jsp\" class=\"nav-link\" href=\"#\">ABOUT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"feedback.jsp\" class=\"nav-link\" href=\"#\">FEEDBACK</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("    \t<li class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"nav-item nav-link\"><button class=\"btn btn-outline-warning\">Login</button></a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class = \"slidewrapper\">\r\n");
      out.write("\t\t<div class=\"slide\" style=\"max-width:auto\">\r\n");
      out.write(" \t\t<img class=\"Slides\" src=\"CSS/img/slide/slide1.jpg\" width=\"1515px\" height=\"475px\">\r\n");
      out.write(" \t\t<img class=\"Slides\" src=\"CSS/img/slide/slide5.jpg\" width=\"1515px\" height=\"475px\">\r\n");
      out.write(" \t\t<img class=\"Slides\" src=\"CSS/img/slide/slide6.jpg\" width=\"1515px\" height=\"475px\">\r\n");
      out.write(" \t\t<img class=\"Slides\" src=\"CSS/img/slide/slide7.jpg\" width=\"1515px\" height=\"475px\">\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<div style=\"text-align:center\">\r\n");
      out.write("\t\t<span class=\"dot\"></span> \r\n");
      out.write("\t\t<span class=\"dot\"></span> \r\n");
      out.write("\t\t<span class=\"dot\"></span> \r\n");
      out.write("\t\t<span class=\"dot\"></span> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\tvar slideIndex = 0;\r\n");
      out.write("\t\tshowSlides();\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showSlides() {\r\n");
      out.write("\t\t\tvar i;\r\n");
      out.write("\t\t\tvar slides = document.getElementsByClassName(\"Slides\");\r\n");
      out.write("\t\t\tvar dots = document.getElementsByClassName(\"dot\");\r\n");
      out.write("\t\t\tfor (i = 0; i < slides.length; i++) {\r\n");
      out.write("\t\t\t\tslides[i].style.display = \"none\";  \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tslideIndex++;\r\n");
      out.write("\t\tif (slideIndex > slides.length) {slideIndex = 1}    \r\n");
      out.write("\t\tfor (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t\t\tdots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tslides[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("\t\tdots[slideIndex-1].className += \" active\";\r\n");
      out.write("\t\tsetTimeout(showSlides, 3000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("        <section id=\"home-icons\" class=\"py-5\" style=\" background-color: #121210;\" >\r\n");
      out.write("            <h2 class=\"text-center text-warning\">Solutions We Offer <i class=\"fas fa-long-arrow-alt-down  mb-2\"></i></h2><br>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service1.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\"  style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Self Drive Rental</h5>\r\n");
      out.write("                                <p class=\"card-text\">A wide range of self drive cars in Sri Lanka from economical to luxury on daily, weekly terms.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service4.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\"  style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Tours / Chauffeur Driven</h5>\r\n");
      out.write("                                <p class=\"card-text\">A unique range of chauffeur driven cars that exceedingly surpass the norm on daily, weekly terms. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service5.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\"  style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Airport / City Transfers</h5>\r\n");
      out.write("                                <p class=\"card-text\">We offer city and airport transfers in Sri Lanka from the Colombo International Airport to any location in the island. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service6.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\" style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Weddings / Events</h5>\r\n");
      out.write("                                <p class=\"card-text\">A fleet of luxury wedding cars in Sri Lanka, we are well geared for weddings and special occasions.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service3.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\"  style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Optional Equipment</h5>\r\n");
      out.write("                                <p class=\"card-text\">We offer a wide range of optional equipment for those searching for a rent a car service in Sri Lanka.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 mb-4 text-center\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <img src=\"CSS/img/service/service7.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\"  style=\"background:#d19d19;\">\r\n");
      out.write("                                <h5 class=\"card-title\">Road Side Assistance</h5>\r\n");
      out.write("                                <p class=\"card-text\">We offer 24/7/365 roadside assistance islandwide with a team ready for action &nbsp; &nbsp; &nbsp;&nbsp;[ 1st time in Sri Lanka ]</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Bottom Start -->\r\n");
      out.write("    <section id=\"adddriver\" class=\"py-5\" style=\" background-color: #242422;\">\r\n");
      out.write("\t\t\t<div class=\"footer-bottom-area\">\r\n");
      out.write("      \t\t\t  <div class=\"container\">\r\n");
      out.write("      \t\t     \t <div class=\"row\">\r\n");
      out.write("        \t        \t<div class=\"col-lg-12 text-center\">\r\n");
      out.write("                   \t\t\t <p style=\"color: #8a8a7c;\">Copyright &copy; <script>document.write(new Date().getFullYear());</script> All Rights Reserved | Sri Lanka</p>\r\n");
      out.write("                \t\t</div>\r\n");
      out.write("           \t\t\t </div>\r\n");
      out.write("        \t\t  </div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("  \t </section>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\t</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
