/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-15 07:33:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\"> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://bootswatch.com/4/slate/bootstrap.min.css\" >\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Nunito\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\" integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/stylesheet.css\">\r\n");
      out.write("         <link rel=\"shortcut icon\" href=\"CSS/favicon.ico\" type=\"image/x-icon\" /> \r\n");
      out.write("         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("         <style>\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("  display: -ms-flexbox; /* IE10 */\r\n");
      out.write("  display: flex;\r\n");
      out.write("  -ms-flex-wrap: wrap; /* IE10 */\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("  margin: 0 -16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-25 {\r\n");
      out.write("  -ms-flex: 25%; /* IE10 */\r\n");
      out.write("  flex: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-50 {\r\n");
      out.write("  -ms-flex: 50%; /* IE10 */\r\n");
      out.write("  flex: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-75 {\r\n");
      out.write("  -ms-flex: 75%; /* IE10 */\r\n");
      out.write("  flex: 75%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-25,\r\n");
      out.write(".col-50,\r\n");
      out.write(".col-75 {\r\n");
      out.write("  padding: 0 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container1 {\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 5px 20px 15px 20px;\r\n");
      out.write("  border: 1px solid lightgrey;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-container {\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 7px 0;\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("  background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  color: #2196F3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("  border: 1px solid lightgrey;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.ex1 {\r\n");
      out.write("  width: 500px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.price {\r\n");
      out.write("  float: right;\r\n");
      out.write("  color: grey;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the \"cart\" column go on top) */\r\n");
      out.write("@media (max-width: 800px) {\r\n");
      out.write("  .row {\r\n");
      out.write("    flex-direction: column-reverse;\r\n");
      out.write("  }\r\n");
      out.write("  .col-25 {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t<title>Add a Booking</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(" body{\r\n");
      out.write("  font-family: 'Nunito';\r\n");
      out.write("  background-image:url(images/img17.jpg);\r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  background-attachment:fixed;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body onload=\"startTime()\">  \r\n");
      out.write("\t\t<!--- Clock Display ------> \r\n");
      out.write("        <script>\r\n");
      out.write("            function startTime() {\r\n");
      out.write("                var today = new Date();\r\n");
      out.write("                var h = today.getHours();\r\n");
      out.write("                var m = today.getMinutes();\r\n");
      out.write("                var s = today.getSeconds();\r\n");
      out.write("                m = checkTime(m);\r\n");
      out.write("                s = checkTime(s);\r\n");
      out.write("                document.getElementById('txt').innerHTML =\r\n");
      out.write("                        h + \":\" + m + \":\" + s;\r\n");
      out.write("                var t = setTimeout(startTime, 500);\r\n");
      out.write("            }\r\n");
      out.write("            function checkTime(i) {\r\n");
      out.write("                if (i < 10) {\r\n");
      out.write("                    i = \"0\" + i\r\n");
      out.write("                }\r\n");
      out.write("                ;  // add zero in front of numbers < 10\r\n");
      out.write("                return i;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <!------------------------------->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"preloader bg-dark text-light\" >\r\n");
      out.write("            <div class=\"preloader-spinner\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div id=\"header-top\" class=\"d-none d-xl-block\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"loader-content\">\r\n");
      out.write("                                <!--<img src=\"assets/img/preloader.gif\">-->\r\n");
      out.write("                                <p id=\"txt\"></p>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-left \">\r\n");
      out.write("                                <i class=\"fas fa-map-marker-alt\"></i> &nbsp; Orex Shopping Complex, Ja-Ela\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"fas fa-phone-volume\"></i> 0112 249 249\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"far fa-clock\"></i> Mon-Fri 09.00 - 17.00\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"header-social-icons text-right\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-facebook\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>&nbsp;\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("         <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t\t<div class=\"col-lg-4\">\r\n");
      out.write("                        <a href=\"Home.jsp\" class=\"logo\">\r\n");
      out.write("                            <img src=\"CSS/img/logo.png\" alt=\"JSOFT\">\r\n");
      out.write("                        </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("  \t\t<div class=\"collapse navbar-collapse\" id=\"navbarColor02\">\r\n");
      out.write("    \t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("        <li class=\"nav-item active\">\r\n");
      out.write("        <a href=\"Home.jsp\" class=\"nav-link\" href=\"#\">HOME </a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"vehicles.jsp\" class=\"nav-link\" href=\"#\">AVAILABLE VEHICLES</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("         <a href=\"booking.html\" class=\"nav-link\" href=\"#\">BOOK A CAR</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"contactus.html\" class=\"nav-link\" href=\"#\">CONTACT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"aboutus.jsp\" class=\"nav-link\" href=\"#\">ABOUT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"feedback.jsp\" class=\"nav-link\" href=\"#\">FEEDBACK</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("    \t<li class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"nav-item nav-link\"><button class=\"btn btn-outline-warning\">LogOut</button></a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<br/><br/><br/>  \r\n");
      out.write("  \r\n");
      out.write("\t\t\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <div class=\"ex1\">\r\n");
      out.write("  <div class=\"col-50\">\r\n");
      out.write("    <div class=\"container1\">\r\n");
      out.write("      <form action=\"");
      out.print( request.getContextPath() );
      out.write("/PaymentServelet\" method=\"post\">\r\n");
      out.write("          <div class=\"col-50\">\r\n");
      out.write("            <h3>Payment</h3>\r\n");
      out.write("            <label for=\"fname\">Accepted Cards</label>\r\n");
      out.write("            <div class=\"icon-container\">\r\n");
      out.write("              <i class=\"fa fa-cc-visa\" style=\"color:navy;\"></i>\r\n");
      out.write("              <i class=\"fa fa-cc-amex\" style=\"color:blue;\"></i>\r\n");
      out.write("              <i class=\"fa fa-cc-mastercard\" style=\"color:red;\"></i>\r\n");
      out.write("              <i class=\"fa fa-cc-discover\" style=\"color:orange;\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <label for=\"cname\">First Name on Card</label>\r\n");
      out.write("            <input type=\"text\" id=\"cname\" name=\"firstName\" placeholder=\"John\">\r\n");
      out.write("            <label for=\"cname\">Last Name on Card</label>\r\n");
      out.write("            <input type=\"text\" id=\"cname\" name=\"lastName\" placeholder=\"Doe\">\r\n");
      out.write("            <label for=\"ccnum\">Credit card number</label>\r\n");
      out.write("            <input type=\"text\" id=\"ccnum\" name=\"cardNo\" placeholder=\"1111-2222-3333-4444\">\r\n");
      out.write("            <label for=\"expmonth\">Exp Date</label>\r\n");
      out.write("            <input type=\"text\" id=\"expmonth\" name=\"expDate\" placeholder=\"MM/YY\">\r\n");
      out.write("            <label for=\"cvv\">CVV</label>\r\n");
      out.write("            <input type=\"text\" id=\"cvv\" name=\"ccv\" placeholder=\"352\">\r\n");
      out.write("            <label for=\"cvv\">Contact</label>\r\n");
      out.write("            <input type=\"text\" id=\"cname\" name=\"contact\" placeholder=\"94 77 000 000 0\">\r\n");
      out.write("        <input type=\"submit\" value=\"Continue to checkout\" class=\"btn\">\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <br/><br/><br/> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
