/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2020-05-13 15:17:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vehicles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://bootswatch.com/4/slate/bootstrap.min.css\" >\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Nunito\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\" integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"CSS/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("        \r\n");
      out.write("  <title>Available vehicles</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"CSS/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"css/heroic-features.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(" body{\r\n");
      out.write("  font-family: 'Nunito';\r\n");
      out.write("  background-image:url(images/veh/abc.jpg);\r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  background-attachment:fixed;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body onload=\"startTime()\">\r\n");
      out.write("<!--- Clock Display ------> \r\n");
      out.write("        <script>\r\n");
      out.write("            function startTime() {\r\n");
      out.write("                var today = new Date();\r\n");
      out.write("                var h = today.getHours();\r\n");
      out.write("                var m = today.getMinutes();\r\n");
      out.write("                var s = today.getSeconds();\r\n");
      out.write("                m = checkTime(m);\r\n");
      out.write("                s = checkTime(s);\r\n");
      out.write("                document.getElementById('txt').innerHTML =\r\n");
      out.write("                        h + \":\" + m + \":\" + s;\r\n");
      out.write("                var t = setTimeout(startTime, 500);\r\n");
      out.write("            }\r\n");
      out.write("            function checkTime(i) {\r\n");
      out.write("                if (i < 10) {\r\n");
      out.write("                    i = \"0\" + i\r\n");
      out.write("                }\r\n");
      out.write("                ;  // add zero in front of numbers < 10\r\n");
      out.write("                return i;\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <!------------------------------->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"preloader bg-dark text-light\" >\r\n");
      out.write("            <div class=\"preloader-spinner\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div id=\"header-top\" class=\"d-none d-xl-block\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"loader-content\">\r\n");
      out.write("                                <!--<img src=\"CSS/img/preloader.gif\">-->\r\n");
      out.write("                                <p id=\"txt\"></p>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-left \">\r\n");
      out.write("                                <i class=\"fas fa-map-marker-alt\"></i> &nbsp; Orex Shopping Complex, Ja-Ela\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"fas fa-phone-volume\"></i> 0112 249 249\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-lg-3 text-center\">\r\n");
      out.write("                                <i class=\"far fa-clock\"></i> Mon-Fri 09.00 - 17.00\r\n");
      out.write("                            </div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"header-social-icons text-right\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-facebook\"></i></a>&nbsp;\r\n");
      out.write("                                <a href=\"#\"><i class=\"fab fa-youtube\"></i></a>&nbsp;\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write(" \t\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("\t\t<div class=\"col-lg-4\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("                            <img src=\"CSS/img/logo.png\" alt=\"JSOFT\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("  \t\t<div class=\"collapse navbar-collapse\" id=\"navbarColor02\">\r\n");
      out.write("    \t<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("        <li class=\"nav-item active\">\r\n");
      out.write("        <a href=\"Home.jsp\" class=\"nav-link\" href=\"#\">HOME </a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"vehicles.html\" class=\"nav-link\" href=\"vehicles.jsp\">AVAILABLE VEHICLES</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("         <a href=\"booking.html\" class=\"nav-link\" href=\"#\">BOOK A CAR</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"contactus.html\" class=\"nav-link\" href=\"#\">CONTACT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"aboutus.jsp\" class=\"nav-link\" href=\"#\">ABOUT US</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("      \t<li class=\"nav-item\">\r\n");
      out.write("        <a href=\"feedback.jsp\" class=\"nav-link\" href=\"#\">FEEDBACK</a>\r\n");
      out.write("      \t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("    \t<li class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"nav-item nav-link\"><button class=\"btn btn-outline-warning\">Login</button></a>\r\n");
      out.write("    \t</li>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("  \t\t<!-- Page Content -->\r\n");
      out.write("  \t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("  \t\t  <!-- Jumbotron Header -->\r\n");
      out.write("   \t\t <header class=\"jumbotron my-4\">\r\n");
      out.write("    \t <h1 class=\"display-3\">Welcome to CARDOOR</h1>\r\n");
      out.write("     \t <p class=\"lead\">1. Easy Booking</br>Enter Pickup and Drop location to get your cab and estimated fare details..</br></br>\r\n");
      out.write("\t\t\t\t\t  2. Get your cab</br>CARDOOR will find you the nearest available Cab..</br></br>\r\n");
      out.write("\t\t\t\t\t  3. Track Your Cab</br>Know your Cab's location and estimated time of arrival in real-time...</br></br>\r\n");
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("   \t\t   <a href=\"contactus.html\" class=\"btn btn-primary btn-lg\">Call to action!</a>\r\n");
      out.write("\t  \r\n");
      out.write("   \t\t </header>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdocument.getElementByTagName('video').play();\r\n");
      out.write("\t\t</script>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t<!-- Page Features -->\r\n");
      out.write("\r\n");
      out.write("    \t<div class=\"row text-center\">\r\n");
      out.write("\r\n");
      out.write("      \t<div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("\r\n");
      out.write("          \t<img class=\"card-img-top\" src=\"CSS/img\\vehicle\\alto.jpg\" alt=\"Suzuki Alto\">\r\n");
      out.write("\r\n");
      out.write("          \t<div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t    \t <h4 class=\"card-title\">Suzuki Alto</h4>\r\n");
      out.write(" \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t <div class=\"test\">\r\n");
      out.write("          \t  <p class=\"card-text\"> 3 seating capacity.</br>100Km for 2500 (Per day).</br>Rs 20 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("\t\t\t          \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("     \t <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\perodua.jpg\" alt=\"PERODUA (DAIHATSU) AXIA\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">PERODUA (DAIHATSU) AXIA</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\"> 3 seating capacity.</br>100Km for 3000 (Per day).</br>Rs 30 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\celerio.jpg\" alt=\"Suzuki Celerio\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">Suzuki Celerio</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">3 seating capacity.</br>100Km for 3000 (Per day).</br>Rs 30 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\aqua.jpg\" alt=\"Toyota Aqua\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">Toyota Aqua</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">4 seating capacity.</br>100Km for 3500 (Per day).</br>Rs 30 for each extra KM.</p>\r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\axio.jpg\" alt=\"Toyota AXIO\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">Toyota AXIO</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">4 seating capacity.</br>100Km for 4000 (Per day).</br>Rs 30 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\allion.jpg\" alt=\"Toyota Allion\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">Toyota Allion</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">4 seating capacity.</br>100Km for 4500 (Per day).</br>Rs 30 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\mercedes.jpg\" alt=\"MERCEDES BENZ S CLASS AMG\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">MERCEDES BENZ S CLASS AMG</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">With Driver</br>150Km for 22500 (Per day).</br>Rs 35 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\landcruiser.jpg\" alt=\"TOYOTA LAND CRUISER 200 V8\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">TOYOTA LAND CRUISER 200 V8</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">5 seating capacity.</br>150Km for 22000 (Per day).</br>Rs 100 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t  \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\landcruiserprado.jpg\" alt=\"TOYOTA LAND CRUISER PRADO\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">TOYOTA LAND CRUISER PRADO</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">5 seating capacity.</br>150Km for 20000 (Per day).</br>Rs 100 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\montero.jpg\" alt=\"MITSUBISHI MONTERO\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">MITSUBISHI MONTERO</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">5 seating capacity.</br>150Km for 18950 (Per day).</br>Rs 100 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("       <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\xtrail.jpg\" alt=\"NISSAN X TRAIL\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">NISSAN X TRAIL</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">5 seating capacity.</br>150Km for 18500 (Per day).</br>Rs 100 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\Hiace.jpg\" alt=\"TOYOTA REGIUS\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">TOYOTA REGIUS</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">9 seating capacity.</br>150Km for 5000 (Per day).</br>Rs 90 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\L300.jpg\" alt=\"MITSUBISHI L300\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">MITSUBISHI L300</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">6 seating capacity.</br>150Km for 4500 (Per day).</br>Rs 90 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\Hiacehighroof.jpg\" alt=\"TOYOTA GRAND CABIN\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">TOYOTA GRAND CABIN</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">15 seating capacity.</br>150Km for 8950 (Per day).</br>Rs 90 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\coaster.jpg\" alt=\"TOYOTA COASTER LUXURY\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">TOYOTA COASTER LUXURY</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">29 seating capacity.</br>250Km for 10000 (Per day).</br>Rs 90 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"CSS/img\\vehicle\\hilman.jpg\" alt=\"HILLMAN GRAND TOURER (1934)\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">HILLMAN GRAND TOURER (1934)</h4>\r\n");
      out.write("\t\t <div class=\"test\">\r\n");
      out.write("            <p class=\"card-text\">4Hours & 30KMS.</br>100Km for 29500 (only 1day).</br>Rs 90 for each extra KM.</p>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"booking.html\" class=\"btn btn-primary\">Book Now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <div class=\"footer-bottom-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All Rights Reserved | Sri Lanka</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"CSS/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"CSS/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
